# Generated by Django 2.1.15 on 2020-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0002_auto_20200527_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='oTarihi',
            field=models.DateTimeField(auto_now_add=True, db_column='oTarihi', default='2002-01-01 15:00:00', verbose_name='Oluşturulma tarihi'),
            preserve_default=False,
        ),
    ]
