# Generated by Django 2.1.15 on 2020-05-27 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0005_auto_20200527_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='oTarihi',
            field=models.DateTimeField(blank=True, db_column='oTarihi', default=django.utils.timezone.now, verbose_name='Oluşturulma tarihi'),
        ),
    ]
