# Generated by Django 2.1.15 on 2020-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0006_auto_20200527_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keyValue',
            field=models.TextField(db_column='keyValue', default='', max_length=500, verbose_name='Anahtar Değerler :'),
        ),
        migrations.AlterField(
            model_name='video',
            name='oTarihi',
            field=models.DateTimeField(auto_now_add=True, db_column='oTarihi', verbose_name='Oluşturulma tarihi'),
        ),
    ]
