# Generated by Django 2.1.15 on 2020-05-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0008_auto_20200527_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='oTarihi',
            field=models.DateTimeField(auto_now_add=True, db_column='oTarihi', verbose_name='Oluşturulma tarihi'),
        ),
    ]
