# Generated by Django 2.1.15 on 2020-06-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0009_auto_20200529_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attTypeName', models.CharField(max_length=200)),
            ],
        ),
    ]
