# Generated by Django 2.1.15 on 2020-06-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvtys', '0010_atttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.TextField(db_column='att', default='', max_length=500, verbose_name='Anahtar Değerler :')),
                ('sure', models.TextField(db_column='sure', default='', max_length=500, verbose_name='Süre Değerler :')),
                ('attTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vvtys.AttType')),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vvtys.Video')),
            ],
        ),
    ]
